ansible: use cython to fix compile issue on 3.11
fedora 37 uses python 3.11 and pycld (https://pypi.org/project/pycld3/)
only provides wheels for 3.6-3.9. When building pycld3, we ran into

> fatal error: longintrepr.h: No such file or directory

which seems to have been addressed in cython (https://github.com/cython/cython/pull/4428);
we need to install some additional packages and USE_CYTHON=1 pip ... in
order for the build on the target machine to succeed.